# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-12-30 16:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_auto_20181230_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kirrurl',
            name='empty_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 30, 21, 36, 34, 589000)),
        ),
        migrations.AlterField(
            model_name='kirrurl',
            name='shortcode',
            field=models.CharField(default='ABCD', max_length=15),
        ),
    ]
