# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-01-02 03:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0004_auto_20181231_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kirrurl',
            name='empty_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 2, 9, 13, 23, 217000)),
        ),
    ]
