# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-01-09 03:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0005_auto_20190102_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kirrurl',
            name='empty_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 9, 9, 25, 28, 215000)),
        ),
    ]
